//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV00108
    {
        public string ITEMNMBR { get; set; }
        public string CURNCYID { get; set; }
        public string PRCLEVEL { get; set; }
        public string UOFM { get; set; }
        public decimal TOQTY { get; set; }
        public decimal FROMQTY { get; set; }
        public decimal UOMPRICE { get; set; }
        public decimal QTYBSUOM { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
