//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV00111
    {
        public string LOCNCODE { get; set; }
        public short ORDERPOLICY { get; set; }
        public decimal FXDORDRQTY { get; set; }
        public short NMBROFDYS { get; set; }
        public decimal ORDRPNTQTY { get; set; }
        public short REPLENISHMENTMETHOD { get; set; }
        public decimal PRCHSNGLDTM { get; set; }
        public decimal MNFCTRNGFXDLDTM { get; set; }
        public decimal MNFCTRNGVRBLLDTM { get; set; }
        public decimal STAGINGLDTME { get; set; }
        public short PLNNNGTMFNCDYS { get; set; }
        public short DMNDTMFNCPRDS { get; set; }
        public string BUYERID { get; set; }
        public string PLANNERID { get; set; }
        public short FRCSTCNSMPTNPRD { get; set; }
        public byte INCLDDINPLNNNG { get; set; }
        public byte CALCULATEATP { get; set; }
        public byte AUTOCHKATP { get; set; }
        public byte PLNFNLPAB { get; set; }
        public short Move_Out_Fence { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
