//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV00101
    {
        public string ITEMNMBR { get; set; }
        public string ITEMDESC { get; set; }
        public decimal NOTEINDX { get; set; }
        public string ITMSHNAM { get; set; }
        public short ITEMTYPE { get; set; }
        public string ITMGEDSC { get; set; }
        public decimal STNDCOST { get; set; }
        public decimal CURRCOST { get; set; }
        public int ITEMSHWT { get; set; }
        public short DECPLQTY { get; set; }
        public short DECPLCUR { get; set; }
        public string ITMTSHID { get; set; }
        public short TAXOPTNS { get; set; }
        public int IVIVINDX { get; set; }
        public int IVIVOFIX { get; set; }
        public int IVCOGSIX { get; set; }
        public int IVSLSIDX { get; set; }
        public int IVSLDSIX { get; set; }
        public int IVSLRNIX { get; set; }
        public int IVINUSIX { get; set; }
        public int IVINSVIX { get; set; }
        public int IVDMGIDX { get; set; }
        public int IVVARIDX { get; set; }
        public int DPSHPIDX { get; set; }
        public int PURPVIDX { get; set; }
        public int UPPVIDX { get; set; }
        public int IVRETIDX { get; set; }
        public int ASMVRIDX { get; set; }
        public string ITMCLSCD { get; set; }
        public short ITMTRKOP { get; set; }
        public string LOTTYPE { get; set; }
        public byte KPERHIST { get; set; }
        public byte KPTRXHST { get; set; }
        public byte KPCALHST { get; set; }
        public byte KPDSTHST { get; set; }
        public byte ALWBKORD { get; set; }
        public short VCTNMTHD { get; set; }
        public string UOMSCHDL { get; set; }
        public string ALTITEM1 { get; set; }
        public string ALTITEM2 { get; set; }
        public string USCATVLS_1 { get; set; }
        public string USCATVLS_2 { get; set; }
        public string USCATVLS_3 { get; set; }
        public string USCATVLS_4 { get; set; }
        public string USCATVLS_5 { get; set; }
        public string USCATVLS_6 { get; set; }
        public short MSTRCDTY { get; set; }
        public System.DateTime MODIFDT { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public short WRNTYDYS { get; set; }
        public string PRCLEVEL { get; set; }
        public string LOCNCODE { get; set; }
        public int PINFLIDX { get; set; }
        public int PURMCIDX { get; set; }
        public int IVINFIDX { get; set; }
        public int INVMCIDX { get; set; }
        public int CGSINFLX { get; set; }
        public int CGSMCIDX { get; set; }
        public string ITEMCODE { get; set; }
        public string TCC { get; set; }
        public string PriceGroup { get; set; }
        public short PRICMTHD { get; set; }
        public string PRCHSUOM { get; set; }
        public string SELNGUOM { get; set; }
        public short KTACCTSR { get; set; }
        public string LASTGENSN { get; set; }
        public short ABCCODE { get; set; }
        public byte Revalue_Inventory { get; set; }
        public int Tolerance_Percentage { get; set; }
        public string Purchase_Item_Tax_Schedu { get; set; }
        public short Purchase_Tax_Options { get; set; }
        public short ITMPLNNNGTYP { get; set; }
        public short STTSTCLVLPRCNTG { get; set; }
        public string CNTRYORGN { get; set; }
        public byte INACTIVE { get; set; }
        public short MINSHELF1 { get; set; }
        public short MINSHELF2 { get; set; }
        public byte INCLUDEINDP { get; set; }
        public byte LOTEXPWARN { get; set; }
        public short LOTEXPWARNDAYS { get; set; }
        public string LASTGENLOT { get; set; }
        public decimal Lot_Split_Quantity { get; set; }
        public byte UseQtyOverageTolerance { get; set; }
        public byte UseQtyShortageTolerance { get; set; }
        public int QtyOverTolerancePercent { get; set; }
        public int QtyShortTolerancePercent { get; set; }
        public int IVSCRVIX { get; set; }
        public string USERID { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
