//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IV40202
    {
        public string UOMSCHDL { get; set; }
        public string UOFM { get; set; }
        public int SEQNUMBR { get; set; }
        public string EQUIVUOM { get; set; }
        public decimal EQUOMQTY { get; set; }
        public decimal QTYBSUOM { get; set; }
        public string UOFMLONGDESC { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
