//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TWOEntities : DbContext
    {
        public TWOEntities()
            : base("name=TWOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RM00101> RM00101 { get; set; }
        public virtual DbSet<IV00102> IV00102 { get; set; }
        public virtual DbSet<IV00108> IV00108 { get; set; }
        public virtual DbSet<IV00111> IV00111 { get; set; }
        public virtual DbSet<IV40202> IV40202 { get; set; }
        public virtual DbSet<RM00102> RM00102 { get; set; }
        public virtual DbSet<RM00301> RM00301 { get; set; }
        public virtual DbSet<SY01200> SY01200 { get; set; }
        public virtual DbSet<TX00101> TX00101 { get; set; }
        public virtual DbSet<TX00201> TX00201 { get; set; }
        public virtual DbSet<IV00101> IV00101 { get; set; }
        public virtual DbSet<TX00102> TX00102 { get; set; }
    }
}
