//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RM00301
    {
        public string SLPRSNID { get; set; }
        public string EMPLOYID { get; set; }
        public string VENDORID { get; set; }
        public string SLPRSNFN { get; set; }
        public string SPRSNSMN { get; set; }
        public string SPRSNSLN { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAX { get; set; }
        public byte INACTIVE { get; set; }
        public string SALSTERR { get; set; }
        public string COMMCODE { get; set; }
        public short COMPRCNT { get; set; }
        public short STDCPRCT { get; set; }
        public short COMAPPTO { get; set; }
        public decimal COSTTODT { get; set; }
        public decimal CSTLSTYR { get; set; }
        public decimal TTLCOMTD { get; set; }
        public decimal TTLCOMLY { get; set; }
        public decimal COMSLTDT { get; set; }
        public decimal COMSLLYR { get; set; }
        public decimal NCOMSLTD { get; set; }
        public decimal NCOMSLYR { get; set; }
        public byte KPCALHST { get; set; }
        public byte KPERHIST { get; set; }
        public decimal NOTEINDX { get; set; }
        public System.DateTime MODIFDT { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public short COMMDEST { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
