//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY01200
    {
        public string Master_Type { get; set; }
        public string Master_ID { get; set; }
        public string ADRSCODE { get; set; }
        public string INET1 { get; set; }
        public string INET2 { get; set; }
        public string INET3 { get; set; }
        public string INET4 { get; set; }
        public string INET5 { get; set; }
        public string INET6 { get; set; }
        public string INET7 { get; set; }
        public string INET8 { get; set; }
        public string Messenger_Address { get; set; }
        public System.DateTime DEX_ROW_TS { get; set; }
        public int DEX_ROW_ID { get; set; }
        public string INETINFO { get; set; }
        public string EmailToAddress { get; set; }
        public string EmailCcAddress { get; set; }
        public string EmailBccAddress { get; set; }
    }
}
