//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX00102
    {
        public string TAXSCHID { get; set; }
        public string TAXDTLID { get; set; }
        public short TXDTLBSE { get; set; }
        public byte TDTAXTAX { get; set; }
        public byte Auto_Calculate { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
