//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorLibrary.Models.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX00201
    {
        public string TAXDTLID { get; set; }
        public string TXDTLDSC { get; set; }
        public short TXDTLTYP { get; set; }
        public int ACTINDX { get; set; }
        public string TXIDNMBR { get; set; }
        public short TXDTLBSE { get; set; }
        public decimal TXDTLPCT { get; set; }
        public decimal TXDTLAMT { get; set; }
        public short TDTLRNDG { get; set; }
        public string TXDBODTL { get; set; }
        public decimal TDTABMIN { get; set; }
        public decimal TDTABMAX { get; set; }
        public decimal TDTAXMIN { get; set; }
        public decimal TDTAXMAX { get; set; }
        public short TDRNGTYP { get; set; }
        public short TXDTQUAL { get; set; }
        public byte TDTAXTAX { get; set; }
        public byte TXDTLPDC { get; set; }
        public string TXDTLPCH { get; set; }
        public byte TXDXDISC { get; set; }
        public string CMNYTXID { get; set; }
        public decimal NOTEINDX { get; set; }
        public string NAME { get; set; }
        public string CNTCPRSN { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAX { get; set; }
        public string TXUSRDF1 { get; set; }
        public string TXUSRDF2 { get; set; }
        public byte VATREGTX { get; set; }
        public byte TaxInvReqd { get; set; }
        public short TaxPostToAcct { get; set; }
        public byte[] TaxBoxes { get; set; }
        public byte IGNRGRSSAMNT { get; set; }
        public decimal TDTABPCT { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
